version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:22.12.0-browsers
    working_directory: ~/project

jobs:
  cypress-tests:
    executor: node-executor
    steps:
      - checkout

      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependencies
          command: npm ci

      - save_cache:
          paths:
            - ~/.npm
          key: npm-cache-{{ checksum "package-lock.json" }}

      - run:
          name: Install Google Chrome and time utility
          command: |
            sudo apt update
            sudo apt install -y wget curl gnupg unzip time
            curl -sSL https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor | sudo tee /usr/share/keyrings/google-linux-signing-keyring.gpg > /dev/null
            echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-linux-signing-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
            sudo apt update
            sudo apt install -y google-chrome-stable
            google-chrome --version

      - run:
          name: Run Cypress tests with CPU usage logging
          command: |
            mkdir -p cypress/results
            /usr/bin/time -v npm run test --browser chrome --reporter mochawesome --reporter-options reportDir=cypress/results 2> cypress/results/cpu_usage.txt || echo "⚠️ Tests failed"

      - run:
          name: Merge Mochawesome reports
          command: |
            npx mochawesome-merge cypress/results/*.json > cypress/results/merged-reports.json || echo "⚠️ No reports to merge"

      - run:
          name: Generate HTML reports
          command: |
            npx mochawesome-report-generator cypress/results/merged-reports.json --reportDir cypress/results --reportFilename test-report.html

      - store_artifacts:
          path: cypress/results
          destination: mochawesome-report

workflows:
  version: 2
  run-cypress-tests:
    jobs:
      - cypress-tests
